### ISSUE TITLE
bind(f,...) without <R> breaks for std function objects in recent MSVC versions under /std:c++latest

### ISSUE THREAD

**Issue by joaquintides** [boostorg/bind#21]
Starting (at least) in MSVC 19.20, `/std:c++latest` results in internal `_HAS_CXX20` macro being defined, which effectively removes `result_type` nested typedef from std library function objects such as `std::equal_to` etc. This breaks code using `boost::bind` without explicit `R` specification.

**Comment by pdimov** [comment]
Wonderful.

**Comment by pdimov** [comment]
This seems a more recent change; Godbolt's 19.20-19.24 still have `result_type`, and so does Appveyor. My local 19.26, however, no longer has it.

**Comment by joaquintides** [comment]
According to VS changelog, the removal happened in [VS 2019 16.6](https://github.com/microsoft/STL/wiki/Changelog#vs-2019-166) (look for P0619R4), which is 19.26, I think.

**Comment by pdimov** [comment]
I believe this has been fixed with https://github.com/boostorg/bind/commit/b601e8924d9d86e18a02fec5418e9696678fb8a8.
